<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.company</groupId>
        <artifactId>platform-parent</artifactId>
        <version>1.0.0</version>
        <relativePath>../../platform-parent/pom.xml</relativePath>
    </parent>

    <artifactId>my-rabbit-starter</artifactId>
    <name>my-rabbit-starter</name>
    <description>RabbitMQ 可靠性：Publisher Confirm、Return 回调、手动 ACK 规范</description>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
        </dependency>
    </dependencies>
</project>
